import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight, Home } from "lucide-react";
import { projects } from "@/data/projects";
import { ProjectCard } from "@/components/projects/project-card";
import { Container } from "@/components/ui/container";
import { CTASection } from "@/components/shared/cta-section";
import { pageMetadata } from "@/lib/seo";
import { absoluteUrl } from "@/lib/utils";

export function generateStaticParams() { return projects.map(p => ({ slug: p.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const item = projects.find(p => p.slug === slug); return item ? pageMetadata(item.title, item.result, `/projects/${slug}`) : {}; }
export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const project = projects.find(p => p.slug === slug); if (!project) notFound(); const related = projects.filter(p => p.slug !== slug).slice(0, 3); const crumb = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: absoluteUrl("/") }, { "@type": "ListItem", position: 2, name: "Projects", item: absoluteUrl("/projects") }, { "@type": "ListItem", position: 3, name: project.title, item: absoluteUrl(`/projects/${slug}`) }] }; return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(crumb) }} /><section className="case-hero"><Image src={project.image} alt={`${project.title} project`} fill priority sizes="100vw" /><div className="case-shade" /><Container><nav className="breadcrumbs"><Link href="/"><Home/>Home</Link><span>/</span><Link href="/projects">Projects</Link><span>/</span><span>{project.title}</span></nav><p className="eyebrow">{project.type} · {project.location}</p><h1>{project.title}</h1><p>{project.products.join(" · ")}</p></Container></section><section className="case-story section-pad"><Container><aside><span>CASE STUDY</span><Link href="/projects"><ArrowLeft/>All projects</Link></aside><div><article><p className="eyebrow">01 · THE CHALLENGE</p><h2>{project.challenge}</h2></article><article><p className="eyebrow">02 · MATERIAL SELECTION & APPROACH</p><h2>{project.approach}</h2><div className="material-tags">{project.products.map(p => <Link href="/products" key={p}>{p}<ArrowUpRight/></Link>)}</div></article><article><p className="eyebrow">03 · FINAL RESULT</p><h2>{project.result}</h2></article></div></Container></section><section className="case-gallery section-pad"><Container><Image src={project.image} alt={`${project.title} wide detail`} width={1600} height={900} /><div><Image src="/images/marble.jpg" alt="Material detail" width={700} height={800} /><Image src="/images/louvers.jpg" alt="Architectural surface detail" width={700} height={800} /></div></Container></section><section className="related-section section-pad"><Container><div className="section-top"><div><p className="eyebrow">NEXT STORIES</p><h2>Related Projects</h2></div></div><div className="projects-grid">{related.map(p => <ProjectCard project={p} key={p.slug} />)}</div></Container></section><CTASection /></>; }
