import type { Metadata } from "next";
import Image from "next/image";
import { Compass, Eye, Gem, Handshake, Layers3, Lightbulb, ShieldCheck } from "lucide-react";
import { PageHero } from "@/components/shared/page-hero";
import { CTASection } from "@/components/shared/cta-section";
import { Reveal } from "@/components/shared/reveal";
import { Container } from "@/components/ui/container";
import { SectionHeading } from "@/components/ui/section-heading";
import { pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata("About Labith Interno", "Discover Labith Interno's material philosophy, values and vision for premium modern interior surfaces.", "/about");

const values = [[Gem, "Product Integrity", "Products are selected with careful attention to appearance, finish and everyday performance."], [Lightbulb, "Design Relevance", "Collections respond to contemporary interiors while leaving room for individual expression."], [Handshake, "Dependable Partnership", "Clear product information and respectful long-term business relationships shape every interaction."], [ShieldCheck, "Responsible Information", "Specifications and recommendations are communicated honestly for informed decisions."]] as const;

export default function AboutPage() { return <><PageHero eyebrow="ABOUT LABITH INTERNO" title="Products That Turn Imagination Into Reality" description="A design-led interior products brand with a growing franchise model." image="/images/fluted-panel-living-room.jpeg" />
  <section className="section-pad"><Container className="editorial-split"><Reveal><div className="portrait-image"><Image src="/images/louvers.jpg" alt="Warm vertical louvers in a contemporary interior" fill sizes="(max-width: 800px) 100vw, 44vw" /></div></Reveal><Reveal className="editorial-copy" delay={.1}><p className="eyebrow">OUR PERSPECTIVE</p><h2>We believe every surface starts with the right product.</h2><p>Labith Interno LLP brings together premium interior products for homes, workplaces, hospitality and retail environments, with a clear focus on product collections and brand availability.</p><p>Our portfolio combines UV marble sheets, soffit panels, WPC doors and frames, WPC sheets, French moldings, louvers, decorative panels and stone-inspired products.</p></Reveal></Container></section>
  <section className="mission-section section-pad"><Container><div className="mission-grid"><Reveal><article><Compass /><p className="eyebrow">MISSION</p><h2>Make premium material choices clearer, more inspiring and more accessible to modern projects.</h2></article></Reveal><Reveal delay={.1}><article><Eye /><p className="eyebrow">VISION</p><h2>Build a trusted interior-products network where design ambition is supported by material knowledge.</h2></article></Reveal></div></Container></section>
  <section className="section-pad"><Container><Reveal><SectionHeading eyebrow="WHAT GUIDES US" title="Values Built Into Every Conversation" description="A practical framework for product, design and partnership decisions." /></Reveal><div className="values-wide">{values.map(([Icon, title, body], i) => <Reveal key={title} delay={i*.06}><article><span>0{i+1}</span><Icon/><h3>{title}</h3><p>{body}</p></article></Reveal>)}</div></Container></section>
  <section className="journey-section section-pad"><Container className="journey-grid"><Reveal><SectionHeading eyebrow="A GROWTH JOURNEY" title="Built for the Next Stage" description="A forward-looking journey that avoids unsupported historical claims while setting a clear direction." /></Reveal><div className="journey-steps"><Reveal><article><span>NOW</span><div><h3>Curate the material portfolio</h3><p>Develop relevant surface collections and structured selection support.</p></div></article></Reveal><Reveal><article><span>NEXT</span><div><h3>Strengthen market access</h3><p>Grow product availability and design relationships across regions.</p></div></article></Reveal><Reveal><article><span>AHEAD</span><div><h3>Build meaningful partnerships</h3><p>Expand through evaluated franchise opportunities and sustained support.</p></div></article></Reveal></div></Container></section>
  <section className="philosophy section-pad"><Container><Layers3/><p className="eyebrow">PRODUCT PHILOSOPHY</p><blockquote>“The best materials do more than cover a surface. They influence light, rhythm, scale and how a space feels.”</blockquote><p>Labith Interno design principle</p></Container></section><CTASection /></>; }
