import type { Metadata } from "next";
import Image from "next/image";
import { BadgeCheck, BarChart3, Check, ClipboardCheck, GraduationCap, Handshake, MapPinned, Megaphone, Rocket, SearchCheck, Store, Users } from "lucide-react";
import { PageHero } from "@/components/shared/page-hero";
import { FranchiseForm } from "@/components/forms/franchise-form";
import { FAQAccordion } from "@/components/shared/faq-accordion";
import { Container } from "@/components/ui/container";
import { SectionHeading } from "@/components/ui/section-heading";
import { Reveal } from "@/components/shared/reveal";
import { franchiseFaqs } from "@/data/faqs";
import { pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata("Franchise Opportunities", "Explore evaluated franchise partnership opportunities with Labith Interno across India.", "/franchise");
const support = [[Megaphone,"Marketing Assistance"],[GraduationCap,"Product & Sales Training"],[Store,"Operational Guidance"],[MapPinned,"Territory Review"],[Users,"Ongoing Business Support"],[BadgeCheck,"Brand Framework"]] as const;
const process = [[ClipboardCheck,"Submit Enquiry"],[Handshake,"Initial Discussion"],[MapPinned,"Location & Territory Review"],[SearchCheck,"Business Evaluation"],[Store,"Agreement & Onboarding"],[Rocket,"Training & Launch Support"]] as const;
export default function FranchisePage() { const faqSchema = { "@context":"https://schema.org","@type":"FAQPage",mainEntity:franchiseFaqs.map(f=>({"@type":"Question",name:f.q,acceptedAnswer:{"@type":"Answer",text:f.a}}))}; return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/><PageHero eyebrow="FRANCHISE PARTNERSHIPS" title="Build Your Future with Labith Interno" description="Join a growing premium interior-products network shaped by strong materials, clear support and a design-led market position." image="/images/retail.jpg" />
  <section className="franchise-intro section-pad"><Container className="franchise-intro-grid"><Reveal><div><p className="eyebrow red-eyebrow">A MARKET BUILT AROUND BETTER SPACES</p><h2>Bring a premium interior product destination to your market.</h2><p>Labith Interno is building a franchise model around relevant products, strong brand presentation, market responsiveness and a considered customer experience.</p></div></Reveal><Reveal delay={.1}><div className="franchise-image"><Image src="/images/fluted-panels-poster2.jpeg" alt="Labith Interno product branding" fill sizes="(max-width: 800px) 100vw, 48vw" /></div></Reveal></Container></section>
  <section className="partner-reasons section-pad"><Container><Reveal><SectionHeading eyebrow="WHY PARTNER" title="A Platform for Considered Growth" description="A proposed support structure designed for long-term brand and market development." /></Reveal><div className="support-grid">{support.map(([Icon,title],i)=><Reveal key={title} delay={i*.05}><article><span>0{i+1}</span><Icon/><h3>{title}</h3><p>Structured guidance aligned to the proposed business format and final partnership agreement.</p></article></Reveal>)}</div></Container></section>
  <section className="ideal-partner section-pad"><Container><div className="ideal-image"><Image src="/images/office.jpg" alt="Interior products business setting" fill sizes="(max-width: 800px) 100vw, 50vw" /></div><div><p className="eyebrow">IDEAL PARTNER PROFILE</p><h2>Local understanding. Customer focus. A taste for good design.</h2><ul><li><Check/>Entrepreneurial and committed to active business operations</li><li><Check/>Strong understanding of the local construction or interiors market</li><li><Check/>Suitable retail or experience-centre location, subject to review</li><li><Check/>Capacity to build a trained, product-focused team</li><li><Check/>Alignment with premium brand presentation standards</li></ul></div></Container></section>
  <section className="process-section section-pad"><Container><Reveal><SectionHeading eyebrow="THE PARTNERSHIP PROCESS" title="A Clear Path from Enquiry to Launch" /></Reveal><div className="process-line">{process.map(([Icon,title],i)=><Reveal className="process-step" key={title} delay={i*.05}><article><span className="process-number">0{i+1}</span><span className="process-icon"><Icon/></span><h3>{title}</h3></article></Reveal>)}</div></Container></section>
  <section className="faq-section section-pad"><Container className="faq-layout"><Reveal><div><p className="eyebrow">FREQUENTLY ASKED</p><h2>Partnership Questions, Answered Clearly</h2><p>No fabricated promises or financial guarantees—commercial details are evaluated and documented formally.</p></div></Reveal><Reveal delay={.1}><FAQAccordion items={franchiseFaqs}/></Reveal></Container></section>
  <section className="franchise-enquiry section-pad"><Container className="form-split"><div><BarChart3/><p className="eyebrow red-eyebrow">TAKE THE FIRST STEP</p><h2>Tell Us About Your Market</h2><p>Share your background, preferred city and business interest. Investment details are available on request.</p><small>Franchise approval, territory allocation, investment requirements and commercial terms are subject to evaluation and formal agreement.</small></div><FranchiseForm/></Container></section></>; }
